apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: bcap-back 
  namespace: cap 
spec:
  replicas: 1
  minReadySeconds: 10 
  selector:
    matchLabels:
      apps: caps 
  template:
    metadata:
      labels:
        apps: caps
    spec:
      terminationGracePeriodSeconds: 10 
      containers:
        - name: back-cont 
          image: mongo 
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: "100m"
              memory: "129Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key:  PORT
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key: SESSION_SECRET
          volumeMounts:
            - name: my-storage
              mountPath: /data/db 
  volumeClaimTemplates:
    - metadata:
        - name: my-storage 
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: "nfs-csi2" 
