apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: cap-frontend
  namespace: cap 
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    app: cap 
  template:
    metadata:
      labels:
        app: cap 
    spec:
      containers:
        - name: cap-cont 
          image: chandu554/cap1:v1.1.0
          port:
            - containerPort: 3015 
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key: PORT
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cap-secret
                  key: SESSION_SECRET