apiVersion: v1 
kind: Service 
metadata:
  name: backend-service 
  namespace: cap
spec:
  selector:
    apps: caps 
  ports:
    - targetPort: 27017 
      port: 27017
  type: ClusterIP
  clusterIP: None      