apiVersion: v1 
kind: Secret 
metadata:
  name: cap-secret
  namespace: cap 
type: Opaque 
stringData:
  MONGO_URI: "mongodb://backend-service:27017/AFF-Docker"

  PORT: "3015"
  SESSION_SECRET: "your-secret-key"